### ISSUE TITLE
Need a way to know if GM notes exist for an entity

### ISSUE THREAD

**Issue by trev33b** [syl3r86/gm-notes#1]
First, I just want to say it's great to be able to bifurcate player notes from GM notes on entities.   

My personal immediate need is to create journal entries that I can partially share with players, while hiding other details.  And your feature works great for that except that it's hard to know whether or not there are any GM notes on a particular entity.  If I have hundreds of entities (I'm already there and I'm still prepping my campaign), that can be a problem.  I might completely forget that I have some nugget of information tucked away and I don't want to have to hit the "GM Notes" button on every entity sheet to check to see if I have something.

So, my suggestion is twofold:

1) At a minimum, find a way to provide an indicator that GM Notes exist (i.e. not empty) for a particular entity that can be seen without first looking at the GM Notes sheet.  Perhaps change the text of the "GM Notes" button to include the indicator.  For example: "GM Notes(*)".   This is probably the easiest solution.

2) Even better is to not have to "leave" the entity application sheet to see the GM notes.  It would be better if you could embed the GM Notes editor into the same screen as the entity   Since every entity sheet has it's own template/sheet, you can't expect to provide a new sheet for every possible case, but you may be able to do a DOM scan to look for usages of the text editor and append your GM notes editor right after it.  It's a bit of a hack, but it would have the advantage of being able to have the GM notes in the same screen.   A similar idea would be to introduce tabs to separate the public vs. GM notes and then put an indicator on the GM Notes tab to show there is info there.

**Comment by syl3r86** [comment]
gm notes now has a checked icon if the entity has notes. I will NOT do any editing of the sheets themselves. it just gets too complicated with too many sheets that can throw in too many unknown problems

**Comment by trev33b** [comment]
I think that'll be sufficient.  Thanks!
