### ISSUE TITLE
Feature Request: Pseudo-encrypted or obfuscated notes

### ISSUE THREAD

**Issue by rcebulko** [syl3r86/gm-notes#10]
@syl3r86 let me know what you think of this; if you think you'd approve it, I'll make the PR.

I run games with my coworkers, all of whom are software engineers who are likely to tinker with their own macros and scripting. I worry about them playing with Journal entities and accidentally finding the unobfuscated `gm-notes` field. What I'd propose:
- move getting/setting the notes into getter/setter helpers
- base64 encode notes in the setter (still visible to players, but they can't accidentally spoil)
- base64 decode notes in the getter
- possibly add a script to update existing Journal entries

Thoughts? If you think this is too irrelevant for the general user I can just run my fork, but I figured it would be generally helpful to any games played by SWEs and open the door to using a simple encryption function if desired (at the risk of DMs locking themselves out).

**Comment by syl3r86** [comment]
too irrelevant for the normal user, so I won't add this. I'd rather keep the module simple.
feel free to keep your own fork running
