### ISSUE TITLE
Using GM Notes as the base for Player Notes.

### ISSUE THREAD

**Issue by techogre** [syl3r86/gm-notes#14]
I was unsure on how to communicate with you, so I'm sending you a note here. I created a Player Note module based on GM Notes. I wanted to reach out and get your permission to do that before I put it out into the wild.

You can see my version here: https://github.com/techogre/player-notes

Thanks!

**Comment by syl3r86** [comment]
thats fine! Go ahead and publish. Thanks for the Attribution =)
