### ISSUE TITLE
Label not showing

### ISSUE THREAD

**Issue by techogre** [syl3r86/gm-notes#15]
Whether the checkbox in the settings for GM Notes is checked or not, the label "GM Notes" never shows. The icon is there and works in both cases.

**Comment by spirritus** [comment]
I can enabel the label, however the option does the exact opposite of what it advertises. If the hide otpion is checked, the label is displayed.

**Comment by techogre** [comment]
I must have done something wrong. It's now showing if the check box is unchecked (i.e. the opposite of what it should be doing, as spirritus said).

**Comment by skepickle** [comment]
I can confirm that the "Hide" checkbox is working opposite from what would be intuitive.

**Comment by syl3r86** [comment]
I'm very sorry about this, just a stupid logic error on my end that I overlooked. its fixed in 0.4.1

**Comment by techogre** [comment]
@syl3r86 Don't knock yourself out over this. Faecal matter happens. :)
We're grateful for all your work on this module.
