### ISSUE TITLE
GM notes are not appearing in with foundry vtt version 9

### ISSUE THREAD

**Issue by Celludriel** [syl3r86/gm-notes#22]
I updated today to foundry VTT version 9 build 238.  The option for gm notes is not appearing anymore on the journal entry.

`TypeError: Cannot read property 'getFlag' of undefined
[Detected 1 package: gm-notes]
    at Function._initEntityHook (gm-notes.js:62)
    at gm-notes.js:162
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at JournalSheet._render (foundry.js:3086)
    at async JournalSheet._render (foundry.js:3733)
    at async JournalSheet._render (foundry.js:49242)`

I believe it has something to do with the following

```
  /**
   * @deprecated since 0.8.0
   * @ignore
   */
	get entity() {
	  console.warn("You are referencing DocumentSheet#entity which has been deprecated in favor of DocumentSheet#document");
	  return this.object;
  }
```

let notes = app.entity.getFlag('gm-notes', 'notes');

might have to become something like

let notes = app.document.getFlag('gm-notes', 'notes');

however entity is used more in the code so maybe on a lot more places ?

**Comment by farling42** [comment]
See a fixed (forked) version available at https://github.com/farling42/gm-notes
until syl gets to fix their version.
