### ISSUE TITLE
Not compatible with FVTT 9.255 & 5e 1.5.7

### ISSUE THREAD

**Issue by mech-tools** [syl3r86/gm-notes#28]
Hello,

A fellow GM reached out to me to make share-media compatible with this module (https://github.com/DarKDinDoN/share-media/issues/4)

Unfortunately, this module doesn't seem to be working with FVTT 9.255 & 5e 1.5.7.
Here is the console error when opening a PC sheet:
![image](https://user-images.githubusercontent.com/1687854/159123023-039503fa-45f5-470f-8bdb-c4d68fbfff62.png)

**Comment by Artemisthemp** [comment]
Try replacing your GM notes with https://raw.githubusercontent.com/aikelb/gm-notes/master/module.json , which have the PR applied.

**Comment by mech-tools** [comment]
> Try replacing your GM notes with https://raw.githubusercontent.com/aikelb/gm-notes/master/module.json , which have the PR applied.

Thx! I was able to install this module and implement a feature to support this module.
I close this for now since your PR already exists.
