### ISSUE TITLE
[Feature request] Mark the GM-Notes icon if not empty.

### ISSUE THREAD

**Issue by SalieriC** [syl3r86/gm-notes#6]
If GM Notes are not empty, tint the icon in the header with a colour like red or blue. This would allow the GM to quickly see whether or not he has added any notes in case he forgets.

**Comment by jamescoats** [comment]
Yes please, this would also help with my campaign where we have many GMs using the same notes, and it's easy to miss if there are GM notes. A colour like yellow or red would be perfect.

**Comment by syl3r86** [comment]
The icon already changes when there are notes available (a checknote). Its a concious design decision to NOT color the icon and I want to keep it that way.

**Comment by SalieriC** [comment]
Okay.
You can get and just replace the relevant files from my fork @jamescoats , @brockhaus and @Muji-k
https://github.com/SalieriC/gm-notes
Should be fine with the given license.
